#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloombergPricerService
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Pricing")]
	public partial class PricingDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBBHistoricalPrice(BBHistoricalPrice instance);
    partial void UpdateBBHistoricalPrice(BBHistoricalPrice instance);
    partial void DeleteBBHistoricalPrice(BBHistoricalPrice instance);
    partial void InsertBBHistoricalRequest(BBHistoricalRequest instance);
    partial void UpdateBBHistoricalRequest(BBHistoricalRequest instance);
    partial void DeleteBBHistoricalRequest(BBHistoricalRequest instance);
    partial void InsertBBPricerHost(BBPricerHost instance);
    partial void UpdateBBPricerHost(BBPricerHost instance);
    partial void DeleteBBPricerHost(BBPricerHost instance);
    partial void InsertBBReferenceData(BBReferenceData instance);
    partial void UpdateBBReferenceData(BBReferenceData instance);
    partial void DeleteBBReferenceData(BBReferenceData instance);
    partial void InsertBBIntradayBarPrice(BBIntradayBarPrice instance);
    partial void UpdateBBIntradayBarPrice(BBIntradayBarPrice instance);
    partial void DeleteBBIntradayBarPrice(BBIntradayBarPrice instance);
    partial void InsertBBPriceRequestQueue(BBPriceRequestQueue instance);
    partial void UpdateBBPriceRequestQueue(BBPriceRequestQueue instance);
    partial void DeleteBBPriceRequestQueue(BBPriceRequestQueue instance);
    #endregion
		
		public PricingDataContext() : 
				base(global::BloombergPricerService.Properties.Settings.Default.PricingConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PricingDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PricingDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PricingDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PricingDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BBHistoricalPrice> BBHistoricalPrices
		{
			get
			{
				return this.GetTable<BBHistoricalPrice>();
			}
		}
		
		public System.Data.Linq.Table<BBHistoricalRequest> BBHistoricalRequests
		{
			get
			{
				return this.GetTable<BBHistoricalRequest>();
			}
		}
		
		public System.Data.Linq.Table<BBPricerHost> BBPricerHosts
		{
			get
			{
				return this.GetTable<BBPricerHost>();
			}
		}
		
		public System.Data.Linq.Table<BBReferenceData> BBReferenceDatas
		{
			get
			{
				return this.GetTable<BBReferenceData>();
			}
		}
		
		public System.Data.Linq.Table<VwBloombergPointsUsed> VwBloombergPointsUseds
		{
			get
			{
				return this.GetTable<VwBloombergPointsUsed>();
			}
		}
		
		public System.Data.Linq.Table<BBIntradayBarPrice> BBIntradayBarPrices
		{
			get
			{
				return this.GetTable<BBIntradayBarPrice>();
			}
		}
		
		public System.Data.Linq.Table<BBPriceRequestQueue> BBPriceRequestQueues
		{
			get
			{
				return this.GetTable<BBPriceRequestQueue>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spBloombergPointsUsedUpdate")]
		public ISingleResult<spBloombergPointsUsedUpdateResult> spBloombergPointsUsedUpdate([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> newPointsUsed)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), username, newPointsUsed);
			return ((ISingleResult<spBloombergPointsUsedUpdateResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spInsertUpdateBBHistoricalPrice")]
		public int spInsertUpdateBBHistoricalPrice([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PriceDate", DbType="Date")] System.Nullable<System.DateTime> priceDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BBTicker", DbType="VarChar(64)")] string bBTicker, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BB", DbType="VarChar(20)")] string bB, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LastUpdatedBy", DbType="VarChar(60)")] string lastUpdatedBy, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Last", DbType="Decimal(18,6)")] System.Nullable<decimal> last, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="High", DbType="Decimal(18,6)")] System.Nullable<decimal> high, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Low", DbType="Decimal(18,6)")] System.Nullable<decimal> low, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Open", DbType="Decimal(18,6)")] System.Nullable<decimal> open, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Open_Int", DbType="Int")] System.Nullable<int> open_Int, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Volume", DbType="BigInt")] System.Nullable<long> volume, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PX_DISC_BID", DbType="Decimal(18,6)")] System.Nullable<decimal> pX_DISC_BID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), priceDate, bBTicker, bB, lastUpdatedBy, last, high, low, open, open_Int, volume, pX_DISC_BID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spInsertUpdateBBIntradayBarPrice")]
		public int spInsertUpdateBBIntradayBarPrice([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PriceDate", DbType="Date")] System.Nullable<System.DateTime> priceDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PriceTime", DbType="DateTime")] System.Nullable<System.DateTime> priceTime, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BBTicker", DbType="VarChar(64)")] string bBTicker, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BB", DbType="VarChar(20)")] string bB, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LastUpdatedBy", DbType="VarChar(60)")] string lastUpdatedBy, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Open", DbType="Decimal(18,6)")] System.Nullable<decimal> open, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="High", DbType="Decimal(18,6)")] System.Nullable<decimal> high, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Low", DbType="Decimal(18,6)")] System.Nullable<decimal> low, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Close", DbType="Decimal(18,6)")] System.Nullable<decimal> close, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumEvents", DbType="Int")] System.Nullable<int> numEvents, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Volume", DbType="BigInt")] System.Nullable<long> volume)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), priceDate, priceTime, bBTicker, bB, lastUpdatedBy, open, high, low, close, numEvents, volume);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spInsertUpdateStaticData")]
		public int spInsertUpdateStaticData([global::System.Data.Linq.Mapping.ParameterAttribute(Name="BBTicker", DbType="VarChar(64)")] string bBTicker, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BB", DbType="VarChar(20)")] string bB, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LastUpdatedBy", DbType="VarChar(60)")] string lastUpdatedBy, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FUT_NOTICE_FIRST", DbType="Date")] System.Nullable<System.DateTime> fUT_NOTICE_FIRST, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FUT_LAST_TRADE_DT", DbType="Date")] System.Nullable<System.DateTime> fUT_LAST_TRADE_DT)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), bBTicker, bB, lastUpdatedBy, fUT_NOTICE_FIRST, fUT_LAST_TRADE_DT);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BBHistoricalPrices")]
	public partial class BBHistoricalPrice : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.DateTime _PriceDate;
		
		private System.DateTime _UpdateTime;
		
		private string _BBTicker;
		
		private string _BB;
		
		private string _LastUpdatedBy;
		
		private System.Nullable<decimal> _Last;
		
		private System.Nullable<decimal> _High;
		
		private System.Nullable<decimal> _Low;
		
		private System.Nullable<decimal> _Open;
		
		private System.Nullable<int> _Open_Int;
		
		private System.Nullable<long> _Volume;
		
		private System.Nullable<decimal> _PX_DISC_BID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPriceDateChanging(System.DateTime value);
    partial void OnPriceDateChanged();
    partial void OnUpdateTimeChanging(System.DateTime value);
    partial void OnUpdateTimeChanged();
    partial void OnBBTickerChanging(string value);
    partial void OnBBTickerChanged();
    partial void OnBBChanging(string value);
    partial void OnBBChanged();
    partial void OnLastUpdatedByChanging(string value);
    partial void OnLastUpdatedByChanged();
    partial void OnLastChanging(System.Nullable<decimal> value);
    partial void OnLastChanged();
    partial void OnHighChanging(System.Nullable<decimal> value);
    partial void OnHighChanged();
    partial void OnLowChanging(System.Nullable<decimal> value);
    partial void OnLowChanged();
    partial void OnOpenChanging(System.Nullable<decimal> value);
    partial void OnOpenChanged();
    partial void OnOpen_IntChanging(System.Nullable<int> value);
    partial void OnOpen_IntChanged();
    partial void OnVolumeChanging(System.Nullable<long> value);
    partial void OnVolumeChanged();
    partial void OnPX_DISC_BIDChanging(System.Nullable<decimal> value);
    partial void OnPX_DISC_BIDChanged();
    #endregion
		
		public BBHistoricalPrice()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PriceDate", DbType="Date NOT NULL", IsPrimaryKey=true)]
		public System.DateTime PriceDate
		{
			get
			{
				return this._PriceDate;
			}
			set
			{
				if ((this._PriceDate != value))
				{
					this.OnPriceDateChanging(value);
					this.SendPropertyChanging();
					this._PriceDate = value;
					this.SendPropertyChanged("PriceDate");
					this.OnPriceDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateTime", DbType="DateTime NOT NULL")]
		public System.DateTime UpdateTime
		{
			get
			{
				return this._UpdateTime;
			}
			set
			{
				if ((this._UpdateTime != value))
				{
					this.OnUpdateTimeChanging(value);
					this.SendPropertyChanging();
					this._UpdateTime = value;
					this.SendPropertyChanged("UpdateTime");
					this.OnUpdateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BBTicker", DbType="VarChar(64) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string BBTicker
		{
			get
			{
				return this._BBTicker;
			}
			set
			{
				if ((this._BBTicker != value))
				{
					this.OnBBTickerChanging(value);
					this.SendPropertyChanging();
					this._BBTicker = value;
					this.SendPropertyChanged("BBTicker");
					this.OnBBTickerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BB", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string BB
		{
			get
			{
				return this._BB;
			}
			set
			{
				if ((this._BB != value))
				{
					this.OnBBChanging(value);
					this.SendPropertyChanging();
					this._BB = value;
					this.SendPropertyChanged("BB");
					this.OnBBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdatedBy", DbType="VarChar(60)")]
		public string LastUpdatedBy
		{
			get
			{
				return this._LastUpdatedBy;
			}
			set
			{
				if ((this._LastUpdatedBy != value))
				{
					this.OnLastUpdatedByChanging(value);
					this.SendPropertyChanging();
					this._LastUpdatedBy = value;
					this.SendPropertyChanged("LastUpdatedBy");
					this.OnLastUpdatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Last", DbType="Decimal(18,6)")]
		public System.Nullable<decimal> Last
		{
			get
			{
				return this._Last;
			}
			set
			{
				if ((this._Last != value))
				{
					this.OnLastChanging(value);
					this.SendPropertyChanging();
					this._Last = value;
					this.SendPropertyChanged("Last");
					this.OnLastChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_High", DbType="Decimal(18,6)")]
		public System.Nullable<decimal> High
		{
			get
			{
				return this._High;
			}
			set
			{
				if ((this._High != value))
				{
					this.OnHighChanging(value);
					this.SendPropertyChanging();
					this._High = value;
					this.SendPropertyChanged("High");
					this.OnHighChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Low", DbType="Decimal(18,6)")]
		public System.Nullable<decimal> Low
		{
			get
			{
				return this._Low;
			}
			set
			{
				if ((this._Low != value))
				{
					this.OnLowChanging(value);
					this.SendPropertyChanging();
					this._Low = value;
					this.SendPropertyChanged("Low");
					this.OnLowChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Open]", Storage="_Open", DbType="Decimal(18,6)")]
		public System.Nullable<decimal> Open
		{
			get
			{
				return this._Open;
			}
			set
			{
				if ((this._Open != value))
				{
					this.OnOpenChanging(value);
					this.SendPropertyChanging();
					this._Open = value;
					this.SendPropertyChanged("Open");
					this.OnOpenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Open_Int", DbType="Int")]
		public System.Nullable<int> Open_Int
		{
			get
			{
				return this._Open_Int;
			}
			set
			{
				if ((this._Open_Int != value))
				{
					this.OnOpen_IntChanging(value);
					this.SendPropertyChanging();
					this._Open_Int = value;
					this.SendPropertyChanged("Open_Int");
					this.OnOpen_IntChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Volume", DbType="BigInt")]
		public System.Nullable<long> Volume
		{
			get
			{
				return this._Volume;
			}
			set
			{
				if ((this._Volume != value))
				{
					this.OnVolumeChanging(value);
					this.SendPropertyChanging();
					this._Volume = value;
					this.SendPropertyChanged("Volume");
					this.OnVolumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PX_DISC_BID", DbType="Decimal(18,6)")]
		public System.Nullable<decimal> PX_DISC_BID
		{
			get
			{
				return this._PX_DISC_BID;
			}
			set
			{
				if ((this._PX_DISC_BID != value))
				{
					this.OnPX_DISC_BIDChanging(value);
					this.SendPropertyChanging();
					this._PX_DISC_BID = value;
					this.SendPropertyChanged("PX_DISC_BID");
					this.OnPX_DISC_BIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BBHistoricalRequest")]
	public partial class BBHistoricalRequest : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RequestID;
		
		private string _BB;
		
		private string _Ticker;
		
		private System.Nullable<System.DateTime> _StartDate;
		
		private System.Nullable<System.DateTime> _EndDate;
		
		private string _DataService;
		
		private string _Fields;
		
		private System.Nullable<int> _Datapoints;
		
		private System.Nullable<int> _BarInterval;
		
		private string _RequestedBy;
		
		private string _HostReserved;
		
		private bool _Completed;
		
		private bool _Error;
		
		private string _ErrorCategory;
		
		private string _ErrorSubcategory;
		
		private string _ErrorMessage;
		
		private System.Nullable<System.DateTime> _HostAssignedAt;
		
		private System.Nullable<System.DateTime> _LastModifiedAt;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRequestIDChanging(int value);
    partial void OnRequestIDChanged();
    partial void OnBBChanging(string value);
    partial void OnBBChanged();
    partial void OnTickerChanging(string value);
    partial void OnTickerChanged();
    partial void OnStartDateChanging(System.Nullable<System.DateTime> value);
    partial void OnStartDateChanged();
    partial void OnEndDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEndDateChanged();
    partial void OnDataServiceChanging(string value);
    partial void OnDataServiceChanged();
    partial void OnFieldsChanging(string value);
    partial void OnFieldsChanged();
    partial void OnDatapointsChanging(System.Nullable<int> value);
    partial void OnDatapointsChanged();
    partial void OnBarIntervalChanging(System.Nullable<int> value);
    partial void OnBarIntervalChanged();
    partial void OnRequestedByChanging(string value);
    partial void OnRequestedByChanged();
    partial void OnHostReservedChanging(string value);
    partial void OnHostReservedChanged();
    partial void OnCompletedChanging(bool value);
    partial void OnCompletedChanged();
    partial void OnErrorChanging(bool value);
    partial void OnErrorChanged();
    partial void OnErrorCategoryChanging(string value);
    partial void OnErrorCategoryChanged();
    partial void OnErrorSubcategoryChanging(string value);
    partial void OnErrorSubcategoryChanged();
    partial void OnErrorMessageChanging(string value);
    partial void OnErrorMessageChanged();
    partial void OnHostAssignedAtChanging(System.Nullable<System.DateTime> value);
    partial void OnHostAssignedAtChanged();
    partial void OnLastModifiedAtChanging(System.Nullable<System.DateTime> value);
    partial void OnLastModifiedAtChanged();
    #endregion
		
		public BBHistoricalRequest()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RequestID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int RequestID
		{
			get
			{
				return this._RequestID;
			}
			set
			{
				if ((this._RequestID != value))
				{
					this.OnRequestIDChanging(value);
					this.SendPropertyChanging();
					this._RequestID = value;
					this.SendPropertyChanged("RequestID");
					this.OnRequestIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BB", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string BB
		{
			get
			{
				return this._BB;
			}
			set
			{
				if ((this._BB != value))
				{
					this.OnBBChanging(value);
					this.SendPropertyChanging();
					this._BB = value;
					this.SendPropertyChanged("BB");
					this.OnBBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ticker", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Ticker
		{
			get
			{
				return this._Ticker;
			}
			set
			{
				if ((this._Ticker != value))
				{
					this.OnTickerChanging(value);
					this.SendPropertyChanging();
					this._Ticker = value;
					this.SendPropertyChanged("Ticker");
					this.OnTickerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> StartDate
		{
			get
			{
				return this._StartDate;
			}
			set
			{
				if ((this._StartDate != value))
				{
					this.OnStartDateChanging(value);
					this.SendPropertyChanging();
					this._StartDate = value;
					this.SendPropertyChanged("StartDate");
					this.OnStartDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EndDate
		{
			get
			{
				return this._EndDate;
			}
			set
			{
				if ((this._EndDate != value))
				{
					this.OnEndDateChanging(value);
					this.SendPropertyChanging();
					this._EndDate = value;
					this.SendPropertyChanged("EndDate");
					this.OnEndDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataService", DbType="NVarChar(30)")]
		public string DataService
		{
			get
			{
				return this._DataService;
			}
			set
			{
				if ((this._DataService != value))
				{
					this.OnDataServiceChanging(value);
					this.SendPropertyChanging();
					this._DataService = value;
					this.SendPropertyChanged("DataService");
					this.OnDataServiceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fields", DbType="NVarChar(400) NOT NULL", CanBeNull=false)]
		public string Fields
		{
			get
			{
				return this._Fields;
			}
			set
			{
				if ((this._Fields != value))
				{
					this.OnFieldsChanging(value);
					this.SendPropertyChanging();
					this._Fields = value;
					this.SendPropertyChanged("Fields");
					this.OnFieldsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Datapoints", DbType="Int")]
		public System.Nullable<int> Datapoints
		{
			get
			{
				return this._Datapoints;
			}
			set
			{
				if ((this._Datapoints != value))
				{
					this.OnDatapointsChanging(value);
					this.SendPropertyChanging();
					this._Datapoints = value;
					this.SendPropertyChanged("Datapoints");
					this.OnDatapointsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BarInterval", DbType="Int")]
		public System.Nullable<int> BarInterval
		{
			get
			{
				return this._BarInterval;
			}
			set
			{
				if ((this._BarInterval != value))
				{
					this.OnBarIntervalChanging(value);
					this.SendPropertyChanging();
					this._BarInterval = value;
					this.SendPropertyChanged("BarInterval");
					this.OnBarIntervalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RequestedBy", DbType="VarChar(50)")]
		public string RequestedBy
		{
			get
			{
				return this._RequestedBy;
			}
			set
			{
				if ((this._RequestedBy != value))
				{
					this.OnRequestedByChanging(value);
					this.SendPropertyChanging();
					this._RequestedBy = value;
					this.SendPropertyChanged("RequestedBy");
					this.OnRequestedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HostReserved", DbType="VarChar(50)")]
		public string HostReserved
		{
			get
			{
				return this._HostReserved;
			}
			set
			{
				if ((this._HostReserved != value))
				{
					this.OnHostReservedChanging(value);
					this.SendPropertyChanging();
					this._HostReserved = value;
					this.SendPropertyChanged("HostReserved");
					this.OnHostReservedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Completed", DbType="Bit NOT NULL")]
		public bool Completed
		{
			get
			{
				return this._Completed;
			}
			set
			{
				if ((this._Completed != value))
				{
					this.OnCompletedChanging(value);
					this.SendPropertyChanging();
					this._Completed = value;
					this.SendPropertyChanged("Completed");
					this.OnCompletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Error", DbType="Bit NOT NULL")]
		public bool Error
		{
			get
			{
				return this._Error;
			}
			set
			{
				if ((this._Error != value))
				{
					this.OnErrorChanging(value);
					this.SendPropertyChanging();
					this._Error = value;
					this.SendPropertyChanged("Error");
					this.OnErrorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorCategory", DbType="VarChar(70)")]
		public string ErrorCategory
		{
			get
			{
				return this._ErrorCategory;
			}
			set
			{
				if ((this._ErrorCategory != value))
				{
					this.OnErrorCategoryChanging(value);
					this.SendPropertyChanging();
					this._ErrorCategory = value;
					this.SendPropertyChanged("ErrorCategory");
					this.OnErrorCategoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorSubcategory", DbType="VarChar(70)")]
		public string ErrorSubcategory
		{
			get
			{
				return this._ErrorSubcategory;
			}
			set
			{
				if ((this._ErrorSubcategory != value))
				{
					this.OnErrorSubcategoryChanging(value);
					this.SendPropertyChanging();
					this._ErrorSubcategory = value;
					this.SendPropertyChanged("ErrorSubcategory");
					this.OnErrorSubcategoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorMessage", DbType="NVarChar(MAX)")]
		public string ErrorMessage
		{
			get
			{
				return this._ErrorMessage;
			}
			set
			{
				if ((this._ErrorMessage != value))
				{
					this.OnErrorMessageChanging(value);
					this.SendPropertyChanging();
					this._ErrorMessage = value;
					this.SendPropertyChanged("ErrorMessage");
					this.OnErrorMessageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HostAssignedAt", DbType="DateTime")]
		public System.Nullable<System.DateTime> HostAssignedAt
		{
			get
			{
				return this._HostAssignedAt;
			}
			set
			{
				if ((this._HostAssignedAt != value))
				{
					this.OnHostAssignedAtChanging(value);
					this.SendPropertyChanging();
					this._HostAssignedAt = value;
					this.SendPropertyChanged("HostAssignedAt");
					this.OnHostAssignedAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastModifiedAt", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastModifiedAt
		{
			get
			{
				return this._LastModifiedAt;
			}
			set
			{
				if ((this._LastModifiedAt != value))
				{
					this.OnLastModifiedAtChanging(value);
					this.SendPropertyChanging();
					this._LastModifiedAt = value;
					this.SendPropertyChanged("LastModifiedAt");
					this.OnLastModifiedAtChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BBPricerHosts")]
	public partial class BBPricerHost : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _HostName;
		
		private bool _PowerSwitch;
		
		private System.DateTime _Heartbeat;
		
		private string _Version;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnHostNameChanging(string value);
    partial void OnHostNameChanged();
    partial void OnPowerSwitchChanging(bool value);
    partial void OnPowerSwitchChanged();
    partial void OnHeartbeatChanging(System.DateTime value);
    partial void OnHeartbeatChanged();
    partial void OnVersionChanging(string value);
    partial void OnVersionChanged();
    #endregion
		
		public BBPricerHost()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HostName", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string HostName
		{
			get
			{
				return this._HostName;
			}
			set
			{
				if ((this._HostName != value))
				{
					this.OnHostNameChanging(value);
					this.SendPropertyChanging();
					this._HostName = value;
					this.SendPropertyChanged("HostName");
					this.OnHostNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PowerSwitch", DbType="Bit NOT NULL")]
		public bool PowerSwitch
		{
			get
			{
				return this._PowerSwitch;
			}
			set
			{
				if ((this._PowerSwitch != value))
				{
					this.OnPowerSwitchChanging(value);
					this.SendPropertyChanging();
					this._PowerSwitch = value;
					this.SendPropertyChanged("PowerSwitch");
					this.OnPowerSwitchChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Heartbeat", DbType="DateTime NOT NULL")]
		public System.DateTime Heartbeat
		{
			get
			{
				return this._Heartbeat;
			}
			set
			{
				if ((this._Heartbeat != value))
				{
					this.OnHeartbeatChanging(value);
					this.SendPropertyChanging();
					this._Heartbeat = value;
					this.SendPropertyChanged("Heartbeat");
					this.OnHeartbeatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Version", DbType="VarChar(20)")]
		public string Version
		{
			get
			{
				return this._Version;
			}
			set
			{
				if ((this._Version != value))
				{
					this.OnVersionChanging(value);
					this.SendPropertyChanging();
					this._Version = value;
					this.SendPropertyChanged("Version");
					this.OnVersionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BBReferenceData")]
	public partial class BBReferenceData : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _BBTicker;
		
		private string _BB;
		
		private System.DateTime _UpdateTime;
		
		private string _LastUpdatedBy;
		
		private System.Nullable<System.DateTime> _FUT_NOTICE_FIRST;
		
		private System.Nullable<System.DateTime> _FUT_LAST_TRADE_DT;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBBTickerChanging(string value);
    partial void OnBBTickerChanged();
    partial void OnBBChanging(string value);
    partial void OnBBChanged();
    partial void OnUpdateTimeChanging(System.DateTime value);
    partial void OnUpdateTimeChanged();
    partial void OnLastUpdatedByChanging(string value);
    partial void OnLastUpdatedByChanged();
    partial void OnFUT_NOTICE_FIRSTChanging(System.Nullable<System.DateTime> value);
    partial void OnFUT_NOTICE_FIRSTChanged();
    partial void OnFUT_LAST_TRADE_DTChanging(System.Nullable<System.DateTime> value);
    partial void OnFUT_LAST_TRADE_DTChanged();
    #endregion
		
		public BBReferenceData()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BBTicker", DbType="VarChar(64) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string BBTicker
		{
			get
			{
				return this._BBTicker;
			}
			set
			{
				if ((this._BBTicker != value))
				{
					this.OnBBTickerChanging(value);
					this.SendPropertyChanging();
					this._BBTicker = value;
					this.SendPropertyChanged("BBTicker");
					this.OnBBTickerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BB", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string BB
		{
			get
			{
				return this._BB;
			}
			set
			{
				if ((this._BB != value))
				{
					this.OnBBChanging(value);
					this.SendPropertyChanging();
					this._BB = value;
					this.SendPropertyChanged("BB");
					this.OnBBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateTime", DbType="DateTime NOT NULL")]
		public System.DateTime UpdateTime
		{
			get
			{
				return this._UpdateTime;
			}
			set
			{
				if ((this._UpdateTime != value))
				{
					this.OnUpdateTimeChanging(value);
					this.SendPropertyChanging();
					this._UpdateTime = value;
					this.SendPropertyChanged("UpdateTime");
					this.OnUpdateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdatedBy", DbType="VarChar(60)")]
		public string LastUpdatedBy
		{
			get
			{
				return this._LastUpdatedBy;
			}
			set
			{
				if ((this._LastUpdatedBy != value))
				{
					this.OnLastUpdatedByChanging(value);
					this.SendPropertyChanging();
					this._LastUpdatedBy = value;
					this.SendPropertyChanged("LastUpdatedBy");
					this.OnLastUpdatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FUT_NOTICE_FIRST", DbType="Date")]
		public System.Nullable<System.DateTime> FUT_NOTICE_FIRST
		{
			get
			{
				return this._FUT_NOTICE_FIRST;
			}
			set
			{
				if ((this._FUT_NOTICE_FIRST != value))
				{
					this.OnFUT_NOTICE_FIRSTChanging(value);
					this.SendPropertyChanging();
					this._FUT_NOTICE_FIRST = value;
					this.SendPropertyChanged("FUT_NOTICE_FIRST");
					this.OnFUT_NOTICE_FIRSTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FUT_LAST_TRADE_DT", DbType="Date")]
		public System.Nullable<System.DateTime> FUT_LAST_TRADE_DT
		{
			get
			{
				return this._FUT_LAST_TRADE_DT;
			}
			set
			{
				if ((this._FUT_LAST_TRADE_DT != value))
				{
					this.OnFUT_LAST_TRADE_DTChanging(value);
					this.SendPropertyChanging();
					this._FUT_LAST_TRADE_DT = value;
					this.SendPropertyChanged("FUT_LAST_TRADE_DT");
					this.OnFUT_LAST_TRADE_DTChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VwBloombergPointsUsed")]
	public partial class VwBloombergPointsUsed
	{
		
		private System.DateTime _Rundate;
		
		private string _Username;
		
		private int _PointsUsed;
		
		public VwBloombergPointsUsed()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rundate", DbType="Date NOT NULL")]
		public System.DateTime Rundate
		{
			get
			{
				return this._Rundate;
			}
			set
			{
				if ((this._Rundate != value))
				{
					this._Rundate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this._Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PointsUsed", DbType="Int NOT NULL")]
		public int PointsUsed
		{
			get
			{
				return this._PointsUsed;
			}
			set
			{
				if ((this._PointsUsed != value))
				{
					this._PointsUsed = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BBIntradayBarPrices")]
	public partial class BBIntradayBarPrice : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.DateTime _PriceDate;
		
		private System.DateTime _PriceTime;
		
		private System.DateTime _UpdateTime;
		
		private string _BBTicker;
		
		private string _BB;
		
		private string _LastUpdatedBy;
		
		private System.Nullable<decimal> _Open;
		
		private System.Nullable<decimal> _High;
		
		private System.Nullable<decimal> _Low;
		
		private System.Nullable<decimal> _Close;
		
		private System.Nullable<int> _NumEvents;
		
		private System.Nullable<long> _Volume;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPriceDateChanging(System.DateTime value);
    partial void OnPriceDateChanged();
    partial void OnPriceTimeChanging(System.DateTime value);
    partial void OnPriceTimeChanged();
    partial void OnUpdateTimeChanging(System.DateTime value);
    partial void OnUpdateTimeChanged();
    partial void OnBBTickerChanging(string value);
    partial void OnBBTickerChanged();
    partial void OnBBChanging(string value);
    partial void OnBBChanged();
    partial void OnLastUpdatedByChanging(string value);
    partial void OnLastUpdatedByChanged();
    partial void OnOpenChanging(System.Nullable<decimal> value);
    partial void OnOpenChanged();
    partial void OnHighChanging(System.Nullable<decimal> value);
    partial void OnHighChanged();
    partial void OnLowChanging(System.Nullable<decimal> value);
    partial void OnLowChanged();
    partial void OnCloseChanging(System.Nullable<decimal> value);
    partial void OnCloseChanged();
    partial void OnNumEventsChanging(System.Nullable<int> value);
    partial void OnNumEventsChanged();
    partial void OnVolumeChanging(System.Nullable<long> value);
    partial void OnVolumeChanged();
    #endregion
		
		public BBIntradayBarPrice()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PriceDate", DbType="Date NOT NULL")]
		public System.DateTime PriceDate
		{
			get
			{
				return this._PriceDate;
			}
			set
			{
				if ((this._PriceDate != value))
				{
					this.OnPriceDateChanging(value);
					this.SendPropertyChanging();
					this._PriceDate = value;
					this.SendPropertyChanged("PriceDate");
					this.OnPriceDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PriceTime", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime PriceTime
		{
			get
			{
				return this._PriceTime;
			}
			set
			{
				if ((this._PriceTime != value))
				{
					this.OnPriceTimeChanging(value);
					this.SendPropertyChanging();
					this._PriceTime = value;
					this.SendPropertyChanged("PriceTime");
					this.OnPriceTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateTime", DbType="DateTime NOT NULL")]
		public System.DateTime UpdateTime
		{
			get
			{
				return this._UpdateTime;
			}
			set
			{
				if ((this._UpdateTime != value))
				{
					this.OnUpdateTimeChanging(value);
					this.SendPropertyChanging();
					this._UpdateTime = value;
					this.SendPropertyChanged("UpdateTime");
					this.OnUpdateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BBTicker", DbType="VarChar(64) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string BBTicker
		{
			get
			{
				return this._BBTicker;
			}
			set
			{
				if ((this._BBTicker != value))
				{
					this.OnBBTickerChanging(value);
					this.SendPropertyChanging();
					this._BBTicker = value;
					this.SendPropertyChanged("BBTicker");
					this.OnBBTickerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BB", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string BB
		{
			get
			{
				return this._BB;
			}
			set
			{
				if ((this._BB != value))
				{
					this.OnBBChanging(value);
					this.SendPropertyChanging();
					this._BB = value;
					this.SendPropertyChanged("BB");
					this.OnBBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdatedBy", DbType="VarChar(60)")]
		public string LastUpdatedBy
		{
			get
			{
				return this._LastUpdatedBy;
			}
			set
			{
				if ((this._LastUpdatedBy != value))
				{
					this.OnLastUpdatedByChanging(value);
					this.SendPropertyChanging();
					this._LastUpdatedBy = value;
					this.SendPropertyChanged("LastUpdatedBy");
					this.OnLastUpdatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Open]", Storage="_Open", DbType="Decimal(18,6)")]
		public System.Nullable<decimal> Open
		{
			get
			{
				return this._Open;
			}
			set
			{
				if ((this._Open != value))
				{
					this.OnOpenChanging(value);
					this.SendPropertyChanging();
					this._Open = value;
					this.SendPropertyChanged("Open");
					this.OnOpenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_High", DbType="Decimal(18,6)")]
		public System.Nullable<decimal> High
		{
			get
			{
				return this._High;
			}
			set
			{
				if ((this._High != value))
				{
					this.OnHighChanging(value);
					this.SendPropertyChanging();
					this._High = value;
					this.SendPropertyChanged("High");
					this.OnHighChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Low", DbType="Decimal(18,6)")]
		public System.Nullable<decimal> Low
		{
			get
			{
				return this._Low;
			}
			set
			{
				if ((this._Low != value))
				{
					this.OnLowChanging(value);
					this.SendPropertyChanging();
					this._Low = value;
					this.SendPropertyChanged("Low");
					this.OnLowChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Close]", Storage="_Close", DbType="Decimal(18,6)")]
		public System.Nullable<decimal> Close
		{
			get
			{
				return this._Close;
			}
			set
			{
				if ((this._Close != value))
				{
					this.OnCloseChanging(value);
					this.SendPropertyChanging();
					this._Close = value;
					this.SendPropertyChanged("Close");
					this.OnCloseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumEvents", DbType="Int")]
		public System.Nullable<int> NumEvents
		{
			get
			{
				return this._NumEvents;
			}
			set
			{
				if ((this._NumEvents != value))
				{
					this.OnNumEventsChanging(value);
					this.SendPropertyChanging();
					this._NumEvents = value;
					this.SendPropertyChanged("NumEvents");
					this.OnNumEventsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Volume", DbType="BigInt")]
		public System.Nullable<long> Volume
		{
			get
			{
				return this._Volume;
			}
			set
			{
				if ((this._Volume != value))
				{
					this.OnVolumeChanging(value);
					this.SendPropertyChanging();
					this._Volume = value;
					this.SendPropertyChanged("Volume");
					this.OnVolumeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BBPriceRequestQueue")]
	public partial class BBPriceRequestQueue : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RequestID;
		
		private string _HostReserved;
		
		private string _BBTicker;
		
		private string _ServiceType;
		
		private string _Fields;
		
		private System.Nullable<System.DateTime> _RequestTS;
		
		private string _RequestedBy;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRequestIDChanging(int value);
    partial void OnRequestIDChanged();
    partial void OnHostReservedChanging(string value);
    partial void OnHostReservedChanged();
    partial void OnBBTickerChanging(string value);
    partial void OnBBTickerChanged();
    partial void OnServiceTypeChanging(string value);
    partial void OnServiceTypeChanged();
    partial void OnFieldsChanging(string value);
    partial void OnFieldsChanged();
    partial void OnRequestTSChanging(System.Nullable<System.DateTime> value);
    partial void OnRequestTSChanged();
    partial void OnRequestedByChanging(string value);
    partial void OnRequestedByChanged();
    #endregion
		
		public BBPriceRequestQueue()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RequestID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int RequestID
		{
			get
			{
				return this._RequestID;
			}
			set
			{
				if ((this._RequestID != value))
				{
					this.OnRequestIDChanging(value);
					this.SendPropertyChanging();
					this._RequestID = value;
					this.SendPropertyChanged("RequestID");
					this.OnRequestIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HostReserved", DbType="VarChar(30)")]
		public string HostReserved
		{
			get
			{
				return this._HostReserved;
			}
			set
			{
				if ((this._HostReserved != value))
				{
					this.OnHostReservedChanging(value);
					this.SendPropertyChanging();
					this._HostReserved = value;
					this.SendPropertyChanged("HostReserved");
					this.OnHostReservedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BBTicker", DbType="VarChar(250)")]
		public string BBTicker
		{
			get
			{
				return this._BBTicker;
			}
			set
			{
				if ((this._BBTicker != value))
				{
					this.OnBBTickerChanging(value);
					this.SendPropertyChanging();
					this._BBTicker = value;
					this.SendPropertyChanged("BBTicker");
					this.OnBBTickerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServiceType", DbType="VarChar(30)")]
		public string ServiceType
		{
			get
			{
				return this._ServiceType;
			}
			set
			{
				if ((this._ServiceType != value))
				{
					this.OnServiceTypeChanging(value);
					this.SendPropertyChanging();
					this._ServiceType = value;
					this.SendPropertyChanged("ServiceType");
					this.OnServiceTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fields", DbType="VarChar(250)")]
		public string Fields
		{
			get
			{
				return this._Fields;
			}
			set
			{
				if ((this._Fields != value))
				{
					this.OnFieldsChanging(value);
					this.SendPropertyChanging();
					this._Fields = value;
					this.SendPropertyChanged("Fields");
					this.OnFieldsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RequestTS", DbType="DateTime")]
		public System.Nullable<System.DateTime> RequestTS
		{
			get
			{
				return this._RequestTS;
			}
			set
			{
				if ((this._RequestTS != value))
				{
					this.OnRequestTSChanging(value);
					this.SendPropertyChanging();
					this._RequestTS = value;
					this.SendPropertyChanged("RequestTS");
					this.OnRequestTSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RequestedBy", DbType="VarChar(30)")]
		public string RequestedBy
		{
			get
			{
				return this._RequestedBy;
			}
			set
			{
				if ((this._RequestedBy != value))
				{
					this.OnRequestedByChanging(value);
					this.SendPropertyChanging();
					this._RequestedBy = value;
					this.SendPropertyChanged("RequestedBy");
					this.OnRequestedByChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class spBloombergPointsUsedUpdateResult
	{
		
		private int _Column1;
		
		public spBloombergPointsUsedUpdateResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="Int NOT NULL")]
		public int Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
